/* ================================================
   seo-data.js — Programmatic SEO Data Layer
   All SEO page definitions, platform metadata,
   multilingual slugs, titles, descriptions & content.
   ================================================ */

/* ─── PLATFORM DEFINITIONS ─── */
const PLATFORMS = {
  youtube: {
    id: "youtube",
    color: "#ff6b6b",
    bgColor: "rgba(255,0,0,.08)",
    borderColor: "rgba(255,0,0,.2)",
    emoji: "▶",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  youtube_mp3: {
    id: "youtube_mp3",
    color: "#ff6b6b",
    bgColor: "rgba(255,0,0,.08)",
    borderColor: "rgba(255,0,0,.2)",
    emoji: "🎵",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  youtube_shorts: {
    id: "youtube_shorts",
    color: "#ff6b6b",
    bgColor: "rgba(255,0,0,.08)",
    borderColor: "rgba(255,0,0,.2)",
    emoji: "⚡",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  tiktok: {
    id: "tiktok",
    color: "#e5e5e5",
    bgColor: "rgba(255,255,255,.05)",
    borderColor: "rgba(255,255,255,.12)",
    emoji: "♪",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  tiktok_mp3: {
    id: "tiktok_mp3",
    color: "#e5e5e5",
    bgColor: "rgba(255,255,255,.05)",
    borderColor: "rgba(255,255,255,.12)",
    emoji: "🎶",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  instagram: {
    id: "instagram",
    color: "#f472b6",
    bgColor: "rgba(200,55,170,.08)",
    borderColor: "rgba(200,55,170,.2)",
    emoji: "◉",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  facebook: {
    id: "facebook",
    color: "#60a5fa",
    bgColor: "rgba(24,119,242,.08)",
    borderColor: "rgba(24,119,242,.2)",
    emoji: "f",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
  twitter: {
    id: "twitter",
    color: "#7dd3fc",
    bgColor: "rgba(29,161,242,.08)",
    borderColor: "rgba(29,161,242,.2)",
    emoji: "𝕏",
    related: [
  "youtube",
  "youtube_mp3",
  "youtube_shorts",
  "tiktok",
  "tiktok_mp3",
  "instagram",
  "facebook",
  "twitter"],
  },
};

/* ─── SEO PAGES MASTER LIST ───
   Each entry: { platform, slug_en, title, description, h1, intro, features }
   Slug is only for English — other languages use the seoSlugs map below.
*/
const SEO_PAGES = [
  {
    platform: "youtube",
    slug_en: "youtube-downloader",
    titles: {
      en: "YouTube Downloader — Download YouTube Videos Free",
      es: "Descargar Videos de YouTube Gratis",
      ar: "تحميل فيديوهات يوتيوب مجاناً",
      pt: "Baixar Vídeos do YouTube Grátis",
      id: "Download Video YouTube Gratis",
      fr: "Télécharger des Vidéos YouTube Gratuitement",
      de: "YouTube Videos kostenlos herunterladen",
      ja: "YouTubeダウンローダー — 無料でYouTube動画をダウンロード",
      tr: "YouTube İndirici — YouTube Videolarını Ücretsiz İndir",
      ru: "Скачать видео с YouTube бесплатно",
      hi: "YouTube वीडियो डाउनलोड करें मुफ्त में",
      vi: "Tải Video YouTube Miễn Phí",
      th: "ดาวน์โหลดวิดีโอ YouTube ฟรี",
      it: "Scaricare Video YouTube Gratis",
      ko: "유튜브 동영상 무료 다운로드",
      fil: "I-download ang YouTube Videos nang Libre",
      pl: "Pobierz Filmy z YouTube Za Darmo",
      nl: "YouTube Video's Gratis Downloaden",
      zh: "免费下载YouTube视频",
      uk: "Завантажити відео з YouTube безкоштовно",
    },
    descriptions: {
      en: "Free YouTube video downloader. Download any YouTube video in MP4 HD quality — no watermark, no registration, works on all devices.",
      es: "Descargador de videos de YouTube gratis. Descarga cualquier video de YouTube en calidad HD MP4.",
      ar: "تحميل فيديو يوتيوب مجاناً. حمّل أي فيديو من يوتيوب بجودة HD بدون علامة مائية.",
      pt: "Baixador de vídeos do YouTube gratuito. Baixe qualquer vídeo do YouTube em qualidade HD MP4.",
      id: "Pengunduh video YouTube gratis. Unduh video YouTube dalam kualitas HD tanpa watermark.",
      fr: "Téléchargeur de vidéos YouTube gratuit. Téléchargez n'importe quelle vidéo YouTube en qualité HD.",
      de: "Kostenloser YouTube-Video-Downloader. Lade YouTube-Videos in HD-Qualität herunter.",
      ja: "無料YouTubeダウンローダー。HD画質でYouTube動画をダウンロード。",
      tr: "Ücretsiz YouTube video indirici. YouTube videolarını HD kalitede indirin.",
      ru: "Бесплатный загрузчик видео YouTube. Скачивайте видео в HD качестве.",
      hi: "मुफ्त YouTube वीडियो डाउनलोडर। HD गुणवत्ता में YouTube वीडियो डाउनलोड करें।",
      vi: "Tải video YouTube miễn phí. Tải xuống video YouTube chất lượng HD.",
      th: "ดาวน์โหลดวิดีโอ YouTube ฟรี คุณภาพ HD ไม่มีลายน้ำ",
      it: "Scarica video YouTube gratis in qualità HD senza filigrana.",
      ko: "무료 유튜브 동영상 다운로더. HD 화질로 유튜브 동영상을 다운로드하세요.",
      fil: "Libreng YouTube video downloader. I-download ang YouTube videos sa HD quality.",
      pl: "Darmowy pobieracz filmów z YouTube. Pobieraj filmy YouTube w jakości HD.",
      nl: "Gratis YouTube video downloader. Download YouTube video's in HD kwaliteit.",
      zh: "免费YouTube视频下载器。以HD画质下载任何YouTube视频。",
      uk: "Безкоштовний завантажувач відео YouTube. Завантажуйте відео у HD якості.",
    },
    h1s: {
      en: "YouTube Video Downloader",
      es: "Descargar Videos de YouTube",
      ar: "تحميل فيديو يوتيوب",
      pt: "Baixar Vídeos do YouTube",
      id: "Download Video YouTube",
      fr: "Télécharger Vidéos YouTube",
      de: "YouTube Videos Herunterladen",
      ja: "YouTube動画ダウンロード",
      tr: "YouTube Video İndirici",
      ru: "Скачать видео с YouTube",
      hi: "YouTube वीडियो डाउनलोडर",
      vi: "Tải Video YouTube",
      th: "ดาวน์โหลดวิดีโอ YouTube",
      it: "Scaricare Video YouTube",
      ko: "유튜브 동영상 다운로드",
      fil: "YouTube Video Downloader",
      pl: "Pobierz Filmy YouTube",
      nl: "YouTube Video Downloaden",
      zh: "下载YouTube视频",
      uk: "Завантажити відео YouTube",
    },
    intros: {
      en: "The fastest and easiest way to download YouTube videos for free. Supports MP4 in Full HD 1080p, 720p, 480p, and 360p. No watermark, no sign-up, no limits.",
      es: "La forma más rápida de descargar videos de YouTube en HD. Sin marca de agua, sin registro.",
      ar: "أسرع وأسهل طريقة لتحميل فيديوهات يوتيوب مجاناً. يدعم MP4 بجودة HD كاملة 1080p.",
      pt: "A maneira mais rápida de baixar vídeos do YouTube em HD. Sem marca d'água, sem cadastro.",
      id: "Cara tercepat untuk mengunduh video YouTube. Mendukung MP4 Full HD 1080p tanpa watermark.",
      fr: "Le moyen le plus rapide pour télécharger des vidéos YouTube en HD. Sans filigrane.",
      de: "Der schnellste Weg, YouTube-Videos in Full HD 1080p herunterzuladen. Kein Wasserzeichen.",
      ja: "YouTubeの動画をフルHD 1080pでダウンロードする最も速い方法。透かしなし。",
      tr: "YouTube videolarını Full HD 1080p'de ücretsiz indirmenin en hızlı yolu.",
      ru: "Самый быстрый способ скачать видео с YouTube в Full HD 1080p без водяного знака.",
      hi: "YouTube वीडियो को Full HD 1080p में मुफ्त डाउनलोड करने का सबसे तेज़ तरीका।",
      vi: "Cách nhanh nhất để tải video YouTube miễn phí. Hỗ trợ Full HD 1080p.",
      th: "วิธีที่เร็วที่สุดในการดาวน์โหลดวิดีโอ YouTube ฟรีในคุณภาพ Full HD 1080p",
      it: "Il modo più veloce per scaricare video YouTube in Full HD 1080p gratis.",
      ko: "유튜브 동영상을 Full HD 1080p로 무료 다운로드하는 가장 빠른 방법.",
      fil: "Ang pinakamabilis na paraan para mag-download ng YouTube videos sa Full HD 1080p.",
      pl: "Najszybszy sposób na pobieranie filmów z YouTube w Full HD 1080p za darmo.",
      nl: "De snelste manier om YouTube video's in Full HD 1080p gratis te downloaden.",
      zh: "免费以Full HD 1080p下载YouTube视频的最快方式，无水印。",
      uk: "Найшвидший спосіб завантажити відео з YouTube у Full HD 1080p безкоштовно.",
    },
    features: ["HD 1080p / 720p / 480p", "MP4 format", "No watermark", "No sign-up", "Fast download", "All devices"],
  },

  {
    platform: "youtube_mp3",
    slug_en: "youtube-mp3-downloader",
    titles: {
      en: "YouTube to MP3 — Free YouTube MP3 Converter & Downloader",
      es: "YouTube a MP3 — Convertidor YouTube MP3 Gratis",
      ar: "يوتيوب إلى MP3 — تحميل صوت يوتيوب مجاناً",
      pt: "YouTube para MP3 — Conversor e Baixador Grátis",
      id: "YouTube ke MP3 — Konverter YouTube MP3 Gratis",
      fr: "YouTube en MP3 — Convertisseur YouTube MP3 Gratuit",
      de: "YouTube zu MP3 — Kostenloser Konverter",
      ja: "YouTubeをMP3に変換 — 無料YouTubeMP3コンバーター",
      tr: "YouTube MP3 — Ücretsiz YouTube MP3 Dönüştürücü",
      ru: "YouTube в MP3 — Бесплатный конвертер YouTube MP3",
      hi: "YouTube to MP3 — मुफ्त YouTube MP3 कन्वर्टर",
      vi: "YouTube sang MP3 — Chuyển đổi YouTube MP3 Miễn Phí",
      th: "YouTube เป็น MP3 — แปลง YouTube MP3 ฟรี",
      it: "YouTube in MP3 — Convertitore YouTube MP3 Gratuito",
      ko: "유튜브 MP3 변환 — 무료 유튜브 MP3 다운로더",
      fil: "YouTube to MP3 — Libreng YouTube MP3 Converter",
      pl: "YouTube do MP3 — Darmowy Konwerter YouTube MP3",
      nl: "YouTube naar MP3 — Gratis YouTube MP3 Converter",
      zh: "YouTube转MP3 — 免费YouTube MP3转换器",
      uk: "YouTube в MP3 — Безкоштовний конвертер YouTube MP3",
    },
    descriptions: {
      en: "Convert any YouTube video to MP3 audio in 320kbps quality. Free, fast, no registration required. Extract music and audio from YouTube instantly.",
      es: "Convierte cualquier video de YouTube a MP3 en alta calidad. Gratis, rápido, sin registro.",
      ar: "حوّل أي فيديو يوتيوب إلى MP3 بجودة 320kbps. مجاني وسريع بدون تسجيل.",
      pt: "Converta qualquer vídeo do YouTube para MP3. Grátis, rápido, sem cadastro.",
      id: "Konversi video YouTube ke MP3 kualitas tinggi. Gratis, cepat, tanpa registrasi.",
      fr: "Convertissez n'importe quelle vidéo YouTube en MP3 haute qualité. Gratuit et rapide.",
      de: "Konvertiere YouTube-Videos in MP3 in 320kbps Qualität. Kostenlos und schnell.",
      ja: "YouTubeの動画を320kbps MP3に変換。無料、高速、登録不要。",
      tr: "Herhangi bir YouTube videosunu 320kbps MP3'e dönüştür. Ücretsiz ve hızlı.",
      ru: "Конвертируйте видео YouTube в MP3 качество 320kbps. Бесплатно и быстро.",
      hi: "YouTube वीडियो को 320kbps MP3 में कन्वर्ट करें। मुफ्त और तेज़।",
      vi: "Chuyển đổi video YouTube sang MP3 chất lượng cao. Miễn phí và nhanh chóng.",
      th: "แปลงวิดีโอ YouTube เป็น MP3 คุณภาพ 320kbps ฟรีและรวดเร็ว",
      it: "Converti qualsiasi video YouTube in MP3 a 320kbps. Gratuito e veloce.",
      ko: "YouTube 동영상을 320kbps MP3로 변환하세요. 무료, 빠름, 가입 불필요.",
      fil: "I-convert ang YouTube videos sa MP3 na may mataas na kalidad. Libre at mabilis.",
      pl: "Konwertuj filmy YouTube do MP3 w jakości 320kbps. Darmowy i szybki.",
      nl: "Converteer YouTube video's naar MP3 in 320kbps kwaliteit. Gratis en snel.",
      zh: "将任何YouTube视频转换为320kbps MP3。免费快速，无需注册。",
      uk: "Конвертуйте відео YouTube у MP3 якість 320kbps. Безкоштовно і швидко.",
    },
    h1s: {
      en: "YouTube to MP3 Converter",
      es: "Convertidor YouTube a MP3",
      ar: "محول يوتيوب إلى MP3",
      pt: "Conversor YouTube para MP3",
      id: "Konverter YouTube ke MP3",
      fr: "Convertisseur YouTube en MP3",
      de: "YouTube zu MP3 Konverter",
      ja: "YouTubeからMP3コンバーター",
      tr: "YouTube MP3 Dönüştürücü",
      ru: "Конвертер YouTube в MP3",
      hi: "YouTube to MP3 कन्वर्टर",
      vi: "Chuyển đổi YouTube sang MP3",
      th: "แปลง YouTube เป็น MP3",
      it: "Convertitore YouTube in MP3",
      ko: "유튜브 MP3 변환기",
      fil: "YouTube to MP3 Converter",
      pl: "Konwerter YouTube do MP3",
      nl: "YouTube naar MP3 Converter",
      zh: "YouTube转MP3转换器",
      uk: "Конвертер YouTube в MP3",
    },
    intros: {
      en: "Extract MP3 audio from any YouTube video or playlist. Get crystal-clear audio up to 320kbps. Perfect for music, podcasts, lectures, and more.",
      es: "Extrae audio MP3 de cualquier video de YouTube. Audio de alta calidad hasta 320kbps.",
      ar: "استخرج صوت MP3 من أي فيديو يوتيوب. صوت عالي الجودة حتى 320kbps.",
      pt: "Extraia áudio MP3 de qualquer vídeo do YouTube. Áudio de alta qualidade até 320kbps.",
      id: "Ekstrak audio MP3 dari video YouTube apapun. Kualitas audio hingga 320kbps.",
      fr: "Extrayez l'audio MP3 de n'importe quelle vidéo YouTube. Jusqu'à 320kbps.",
      de: "Extrahiere MP3-Audio aus jedem YouTube-Video. Bis zu 320kbps Audioqualität.",
      ja: "YouTubeの動画からMP3オーディオを抽出。最大320kbpsの高音質。",
      tr: "Herhangi bir YouTube videosundan MP3 ses çıkar. 320kbps'ye kadar ses kalitesi.",
      ru: "Извлекайте MP3-аудио из любого видео YouTube. Качество до 320kbps.",
      hi: "किसी भी YouTube वीडियो से MP3 ऑडियो निकालें। 320kbps तक की ऑडियो गुणवत्ता।",
      vi: "Trích xuất âm thanh MP3 từ bất kỳ video YouTube nào. Lên đến 320kbps.",
      th: "ดึงเสียง MP3 จากวิดีโอ YouTube ใดก็ได้ คุณภาพสูงถึง 320kbps",
      it: "Estrai audio MP3 da qualsiasi video YouTube. Qualità audio fino a 320kbps.",
      ko: "유튜브 동영상에서 MP3 오디오를 추출하세요. 최대 320kbps의 고음질.",
      fil: "Kunin ang MP3 audio mula sa anumang YouTube video. Hanggang 320kbps.",
      pl: "Ekstrahuj audio MP3 z dowolnego filmu YouTube. Jakość audio do 320kbps.",
      nl: "Extraheer MP3-audio van elk YouTube-video. Tot 320kbps audiokwaliteit.",
      zh: "从任何YouTube视频中提取MP3音频。高达320kbps的高音质。",
      uk: "Витягуйте MP3 аудіо з будь-якого відео YouTube. Якість до 320kbps.",
    },
    features: ["320kbps MP3", "High audio quality", "No registration", "Instant conversion", "Music & podcasts", "Free forever"],
  },

  {
    platform: "youtube_shorts",
    slug_en: "youtube-shorts-downloader",
    titles: {
      en: "YouTube Shorts Downloader — Save YouTube Shorts for Free",
      es: "Descargar YouTube Shorts Gratis",
      ar: "تحميل YouTube Shorts مجاناً",
      pt: "Baixar YouTube Shorts Grátis",
      id: "Download YouTube Shorts Gratis",
      fr: "Télécharger YouTube Shorts Gratuitement",
      de: "YouTube Shorts kostenlos herunterladen",
      ja: "YouTube Shortsを無料でダウンロード",
      tr: "YouTube Shorts İndirici — Ücretsiz Kısa Videoları Kaydet",
      ru: "Скачать YouTube Shorts бесплатно",
      hi: "YouTube Shorts डाउनलोड करें मुफ्त में",
      vi: "Tải YouTube Shorts Miễn Phí",
      th: "ดาวน์โหลด YouTube Shorts ฟรี",
      it: "Scaricare YouTube Shorts Gratis",
      ko: "유튜브 쇼츠 무료 다운로드",
      fil: "I-download ang YouTube Shorts nang Libre",
      pl: "Pobierz YouTube Shorts Za Darmo",
      nl: "YouTube Shorts Gratis Downloaden",
      zh: "免费下载YouTube Shorts",
      uk: "Завантажити YouTube Shorts безкоштовно",
    },
    descriptions: {
      en: "Download YouTube Shorts videos for free. Save any YouTube Short to your device in full quality — no watermark, no app needed.",
      es: "Descarga YouTube Shorts gratis. Guarda cualquier Short en tu dispositivo sin marca de agua.",
      ar: "حمّل YouTube Shorts مجاناً. احفظ أي فيديو قصير على جهازك بدون علامة مائية.",
      pt: "Baixe YouTube Shorts de graça. Salve qualquer Short no seu dispositivo sem marca d'água.",
      id: "Download YouTube Shorts gratis. Simpan video Shorts tanpa watermark.",
      fr: "Téléchargez YouTube Shorts gratuitement. Sauvegardez n'importe quel Short sans filigrane.",
      de: "YouTube Shorts kostenlos herunterladen. Speichern ohne Wasserzeichen.",
      ja: "YouTube Shortsを無料でダウンロード。透かしなしでデバイスに保存。",
      tr: "YouTube Shorts'ları ücretsiz indir. Herhangi bir Shorts'ı filigrансыз kaydet.",
      ru: "Скачайте YouTube Shorts бесплатно. Сохраняйте без водяного знака.",
      hi: "YouTube Shorts मुफ्त में डाउनलोड करें। बिना वॉटरमार्क के।",
      vi: "Tải YouTube Shorts miễn phí. Lưu bất kỳ Short nào không có watermark.",
      th: "ดาวน์โหลด YouTube Shorts ฟรี ไม่มีลายน้ำ",
      it: "Scarica YouTube Shorts gratis senza filigrana.",
      ko: "유튜브 쇼츠를 무료로 다운로드. 워터마크 없이 저장.",
      fil: "I-download ang YouTube Shorts nang libre. Walang watermark.",
      pl: "Pobierz YouTube Shorts za darmo. Bez znaku wodnego.",
      nl: "Download YouTube Shorts gratis. Opslaan zonder watermerk.",
      zh: "免费下载YouTube Shorts，无水印。",
      uk: "Завантажте YouTube Shorts безкоштовно без водяного знаку.",
    },
    h1s: {
      en: "YouTube Shorts Downloader",
      es: "Descargar YouTube Shorts",
      ar: "تحميل YouTube Shorts",
      pt: "Baixar YouTube Shorts",
      id: "Download YouTube Shorts",
      fr: "Télécharger YouTube Shorts",
      de: "YouTube Shorts Herunterladen",
      ja: "YouTube Shorts ダウンロード",
      tr: "YouTube Shorts İndirici",
      ru: "Скачать YouTube Shorts",
      hi: "YouTube Shorts डाउनलोडर",
      vi: "Tải YouTube Shorts",
      th: "ดาวน์โหลด YouTube Shorts",
      it: "Scaricare YouTube Shorts",
      ko: "유튜브 쇼츠 다운로드",
      fil: "YouTube Shorts Downloader",
      pl: "Pobierz YouTube Shorts",
      nl: "YouTube Shorts Downloaden",
      zh: "下载YouTube Shorts",
      uk: "Завантажити YouTube Shorts",
    },
    intros: {
      en: "Download any YouTube Shorts video instantly. Full quality, no watermarks, no app installation needed. Works on mobile and desktop.",
      es: "Descarga cualquier YouTube Shorts al instante. Calidad completa, sin marcas de agua.",
      ar: "حمّل أي فيديو YouTube Shorts فوراً. جودة كاملة بدون علامات مائية.",
      pt: "Baixe qualquer YouTube Shorts instantaneamente. Qualidade total, sem marcas d'água.",
      id: "Unduh YouTube Shorts kapan saja. Kualitas penuh, tanpa watermark.",
      fr: "Téléchargez n'importe quel YouTube Shorts instantanément. Qualité totale.",
      de: "Lade jeden YouTube Shorts sofort herunter. Volle Qualität, keine Wasserzeichen.",
      ja: "YouTubeのShortsをすぐにダウンロード。フル画質、透かしなし。",
      tr: "Herhangi bir YouTube Shorts'ı anında indir. Tam kalite, filigransız.",
      ru: "Скачивайте любые YouTube Shorts мгновенно. Полное качество, без водяных знаков.",
      hi: "किसी भी YouTube Shorts को तुरंत डाउनलोड करें। पूरी गुणवत्ता, बिना वॉटरमार्क।",
      vi: "Tải xuống bất kỳ YouTube Shorts nào ngay lập tức. Chất lượng đầy đủ.",
      th: "ดาวน์โหลด YouTube Shorts ใดก็ได้ทันที คุณภาพเต็ม ไม่มีลายน้ำ",
      it: "Scarica qualsiasi YouTube Shorts istantaneamente. Qualità totale, senza filigrana.",
      ko: "YouTube Shorts를 즉시 다운로드. 전체 화질, 워터마크 없음.",
      fil: "I-download ang anumang YouTube Shorts agad. Full quality, walang watermark.",
      pl: "Pobierz dowolny YouTube Shorts natychmiast. Pełna jakość, bez znaku wodnego.",
      nl: "Download elke YouTube Shorts onmiddellijk. Volledige kwaliteit, geen watermerk.",
      zh: "立即下载任何YouTube Shorts视频。全质量，无水印。",
      uk: "Завантажуйте будь-який YouTube Shorts миттєво. Повна якість, без водяного знаку.",
    },
    features: ["Vertical video support", "Full quality", "No watermark", "Works on mobile", "Fast download", "No app needed"],
  },

  {
    platform: "tiktok",
    slug_en: "tiktok-downloader",
    titles: {
      en: "TikTok Downloader — Download TikTok Videos No Watermark",
      es: "Descargar Videos de TikTok sin Marca de Agua",
      ar: "تحميل فيديو تيك توك بدون علامة مائية",
      pt: "Baixar Vídeos do TikTok sem Marca d'Água",
      id: "Download Video TikTok Tanpa Watermark",
      fr: "Télécharger TikTok Sans Filigrane",
      de: "TikTok Videos ohne Wasserzeichen herunterladen",
      ja: "TikTokビデオをウォーターマークなしでダウンロード",
      tr: "TikTok İndirici — Filigrансız TikTok Video İndir",
      ru: "Скачать TikTok без водяного знака",
      hi: "TikTok वीडियो डाउनलोड करें बिना वॉटरमार्क के",
      vi: "Tải TikTok Không Có Watermark",
      th: "ดาวน์โหลด TikTok ไม่มีลายน้ำ",
      it: "Scaricare TikTok Senza Filigrana",
      ko: "틱톡 동영상 워터마크 없이 다운로드",
      fil: "I-download ang TikTok Videos Walang Watermark",
      pl: "Pobierz TikTok Bez Znaku Wodnego",
      nl: "TikTok Downloaden Zonder Watermerk",
      zh: "下载TikTok视频无水印",
      uk: "Завантажити TikTok без водяного знаку",
    },
    descriptions: {
      en: "Download TikTok videos without watermark for free. Save TikTok videos in HD quality directly to your device. No registration required.",
      es: "Descarga videos de TikTok sin marca de agua. Guarda en alta calidad directamente en tu dispositivo.",
      ar: "حمّل مقاطع تيك توك بدون علامة مائية مجاناً. احفظها بجودة عالية على جهازك.",
      pt: "Baixe vídeos TikTok sem marca d'água. Alta qualidade, sem registro.",
      id: "Unduh video TikTok tanpa watermark. Kualitas HD langsung ke perangkat Anda.",
      fr: "Téléchargez des vidéos TikTok sans filigrane en haute qualité.",
      de: "Lade TikTok-Videos ohne Wasserzeichen herunter. HD-Qualität, kostenlos.",
      ja: "TikTokの動画をウォーターマークなしでダウンロード。HD画質で保存。",
      tr: "TikTok videolarını filigrансыз indirin. HD kalitede, ücretsiz.",
      ru: "Скачивайте TikTok без водяного знака в HD качестве. Бесплатно.",
      hi: "TikTok वीडियो बिना वॉटरमार्क के डाउनलोड करें। HD गुणवत्ता।",
      vi: "Tải video TikTok không có watermark. Chất lượng HD, miễn phí.",
      th: "ดาวน์โหลดวิดีโอ TikTok ไม่มีลายน้ำ คุณภาพ HD ฟรี",
      it: "Scarica video TikTok senza filigrana in HD. Gratuito.",
      ko: "TikTok 동영상을 워터마크 없이 HD 화질로 다운로드. 무료.",
      fil: "I-download ang TikTok videos walang watermark sa HD quality.",
      pl: "Pobierz filmy TikTok bez znaku wodnego w jakości HD.",
      nl: "Download TikTok video's zonder watermerk in HD kwaliteit.",
      zh: "无水印下载TikTok视频，高清画质，免费。",
      uk: "Завантажуйте TikTok без водяного знаку у HD якості. Безкоштовно.",
    },
    h1s: {
      en: "TikTok Video Downloader",
      es: "Descargar Videos de TikTok",
      ar: "تحميل فيديو تيك توك",
      pt: "Baixar Vídeos TikTok",
      id: "Download Video TikTok",
      fr: "Télécharger Vidéos TikTok",
      de: "TikTok Videos Herunterladen",
      ja: "TikTokビデオダウンロード",
      tr: "TikTok Video İndirici",
      ru: "Скачать видео TikTok",
      hi: "TikTok वीडियो डाउनलोडर",
      vi: "Tải Video TikTok",
      th: "ดาวน์โหลดวิดีโอ TikTok",
      it: "Scaricare Video TikTok",
      ko: "틱톡 동영상 다운로드",
      fil: "TikTok Video Downloader",
      pl: "Pobierz Filmy TikTok",
      nl: "TikTok Video Downloaden",
      zh: "下载TikTok视频",
      uk: "Завантажити відео TikTok",
    },
    intros: {
      en: "Download TikTok videos without watermark in seconds. Supports all TikTok content including Reels, Stories, and live clips. Fast, free, and unlimited.",
      es: "Descarga videos de TikTok sin marca de agua en segundos. Compatible con todo el contenido de TikTok.",
      ar: "حمّل مقاطع تيك توك بدون علامة مائية في ثوانٍ. يدعم جميع محتوى تيك توك.",
      pt: "Baixe vídeos TikTok sem marca d'água em segundos. Suporta todo o conteúdo TikTok.",
      id: "Unduh video TikTok tanpa watermark dalam hitungan detik. Mendukung semua konten TikTok.",
      fr: "Téléchargez des vidéos TikTok sans filigrane en quelques secondes.",
      de: "Lade TikTok-Videos ohne Wasserzeichen in Sekunden herunter.",
      ja: "TikTokの動画を数秒でウォーターマークなしでダウンロード。",
      tr: "TikTok videolarını saniyeler içinde filigrансыз indir.",
      ru: "Скачивайте TikTok без водяного знака за секунды.",
      hi: "TikTok वीडियो सेकंड में बिना वॉटरमार्क के डाउनलोड करें।",
      vi: "Tải video TikTok không có watermark trong vài giây.",
      th: "ดาวน์โหลดวิดีโอ TikTok ไม่มีลายน้ำในไม่กี่วินาที",
      it: "Scarica video TikTok senza filigrana in pochi secondi.",
      ko: "TikTok 동영상을 몇 초 만에 워터마크 없이 다운로드.",
      fil: "I-download ang TikTok videos walang watermark sa ilang segundo.",
      pl: "Pobieraj filmy TikTok bez znaku wodnego w sekundy.",
      nl: "Download TikTok video's zonder watermerk in seconden.",
      zh: "几秒内下载TikTok视频，无水印。",
      uk: "Завантажуйте TikTok без водяного знаку за секунди.",
    },
    features: ["No watermark", "HD quality", "All TikTok content", "No registration", "Fast & free", "Mobile friendly"],
  },

  {
    platform: "tiktok_mp3",
    slug_en: "tiktok-mp3-downloader",
    titles: {
      en: "TikTok to MP3 — Extract Audio from TikTok Free",
      es: "TikTok a MP3 — Extraer Audio de TikTok Gratis",
      ar: "تيك توك إلى MP3 — استخراج صوت تيك توك مجاناً",
      pt: "TikTok para MP3 — Extrair Áudio Grátis",
      id: "TikTok ke MP3 — Ekstrak Audio TikTok Gratis",
      fr: "TikTok en MP3 — Extraire l'audio TikTok Gratuit",
      de: "TikTok zu MP3 — Audio kostenlos extrahieren",
      ja: "TikTokをMP3に — TikTok音声を無料で抽出",
      tr: "TikTok MP3 — Ücretsiz Ses Çıkar",
      ru: "TikTok в MP3 — Извлечь аудио бесплатно",
      hi: "TikTok to MP3 — TikTok से ऑडियो निकालें",
      vi: "TikTok sang MP3 — Trích xuất âm thanh miễn phí",
      th: "TikTok เป็น MP3 — ดึงเสียงจาก TikTok ฟรี",
      it: "TikTok in MP3 — Estrai audio gratis",
      ko: "TikTok MP3 — TikTok 오디오 추출 무료",
      fil: "TikTok to MP3 — Libreng Audio Extractor",
      pl: "TikTok do MP3 — Ekstraktor audio za darmo",
      nl: "TikTok naar MP3 — Audio Gratis Extraheren",
      zh: "TikTok转MP3 — 免费提取TikTok音频",
      uk: "TikTok в MP3 — Витягнути аудіо безкоштовно",
    },
    descriptions: {
      en: "Extract and download MP3 audio from any TikTok video for free. Get the music or sound from TikTok in high quality. Fast and easy.",
      es: "Extrae y descarga audio MP3 de cualquier TikTok gratis.",
      ar: "استخرج وحمّل صوت MP3 من أي فيديو تيك توك مجاناً.",
      pt: "Extraia e baixe áudio MP3 de qualquer TikTok de graça.",
      id: "Ekstrak dan unduh audio MP3 dari TikTok apapun gratis.",
      fr: "Extrayez et téléchargez l'audio MP3 de n'importe quel TikTok gratuitement.",
      de: "Extrahiere und lade MP3-Audio von jedem TikTok kostenlos.",
      ja: "TikTokの動画からMP3オーディオを無料で抽出。",
      tr: "Herhangi bir TikTok videosundan MP3 ses çıkar. Ücretsiz.",
      ru: "Извлекайте MP3-аудио из любого TikTok. Бесплатно.",
      hi: "किसी भी TikTok वीडियो से MP3 ऑडियो निकालें। मुफ्त।",
      vi: "Trích xuất audio MP3 từ bất kỳ TikTok nào. Miễn phí.",
      th: "ดึงเสียง MP3 จากวิดีโอ TikTok ใดก็ได้ ฟรี",
      it: "Estrai audio MP3 da qualsiasi TikTok. Gratuito.",
      ko: "TikTok 동영상에서 MP3 오디오 추출. 무료.",
      fil: "Kunin ang MP3 audio mula sa anumang TikTok. Libre.",
      pl: "Ekstrahuj audio MP3 z dowolnego TikTok. Darmowy.",
      nl: "Extraheer MP3-audio van elk TikTok. Gratis.",
      zh: "从任何TikTok提取MP3音频。免费。",
      uk: "Витягуйте MP3 аудіо з будь-якого TikTok. Безкоштовно.",
    },
    h1s: {
      en: "TikTok to MP3 Downloader",
      es: "Convertidor TikTok a MP3",
      ar: "محول تيك توك إلى MP3",
      pt: "Conversor TikTok para MP3",
      id: "Konverter TikTok ke MP3",
      fr: "Convertisseur TikTok en MP3",
      de: "TikTok zu MP3 Konverter",
      ja: "TikTokからMP3ダウンローダー",
      tr: "TikTok MP3 Dönüştürücü",
      ru: "Конвертер TikTok в MP3",
      hi: "TikTok to MP3 डाउनलोडर",
      vi: "TikTok sang MP3",
      th: "TikTok เป็น MP3",
      it: "Convertitore TikTok in MP3",
      ko: "틱톡 MP3 다운로더",
      fil: "TikTok to MP3 Downloader",
      pl: "Konwerter TikTok do MP3",
      nl: "TikTok naar MP3 Downloader",
      zh: "TikTok转MP3下载器",
      uk: "TikTok в MP3 завантажувач",
    },
    intros: {
      en: "Turn any TikTok video into an MP3 audio file. Perfect for saving trending sounds, music tracks, and audio clips from TikTok.",
      es: "Convierte cualquier TikTok en MP3. Perfecto para guardar sonidos virales y música de TikTok.",
      ar: "حوّل أي فيديو تيك توك إلى ملف MP3. مثالي لحفظ الأصوات الرائجة والموسيقى.",
      pt: "Converta qualquer TikTok em MP3. Perfeito para salvar sons virais e músicas.",
      id: "Ubah TikTok apapun menjadi MP3. Ideal untuk menyimpan suara viral dan musik TikTok.",
      fr: "Convertissez n'importe quel TikTok en MP3. Idéal pour les sons viraux.",
      de: "Wandle jeden TikTok in MP3 um. Ideal für virale Sounds und Musik.",
      ja: "TikTokをMP3に変換。トレンドサウンドや音楽を保存するのに最適。",
      tr: "Herhangi bir TikTok'u MP3'e dönüştür. Viral sesler ve müzik için mükemmel.",
      ru: "Превратите любой TikTok в MP3. Идеально для трендовых звуков и музыки.",
      hi: "किसी भी TikTok को MP3 में बदलें। ट्रेंडिंग साउंड और म्यूजिक सेव करने के लिए परफेक्ट।",
      vi: "Chuyển đổi bất kỳ TikTok nào thành MP3. Lý tưởng cho âm thanh thịnh hành.",
      th: "แปลง TikTok ใดก็ได้เป็น MP3 เหมาะสำหรับบันทึกเสียงไวรัลและเพลง",
      it: "Converti qualsiasi TikTok in MP3. Ideale per suoni virali e musica.",
      ko: "TikTok을 MP3로 변환. 트렌디한 사운드와 음악 저장에 완벽.",
      fil: "I-convert ang anumang TikTok sa MP3. Para sa mga viral sounds at musika.",
      pl: "Konwertuj dowolny TikTok na MP3. Idealny do wirusowych dźwięków i muzyki.",
      nl: "Converteer elke TikTok naar MP3. Ideaal voor virale geluiden en muziek.",
      zh: "将任何TikTok转换为MP3。非常适合保存热门声音和音乐。",
      uk: "Перетворіть будь-який TikTok у MP3. Ідеально для трендових звуків та музики.",
    },
    features: ["High-quality audio", "Instant extraction", "Trending sounds", "No watermark", "Free unlimited", "All devices"],
  },

  {
    platform: "instagram",
    slug_en: "instagram-reels-downloader",
    titles: {
      en: "Instagram Reels Downloader — Save Instagram Videos Free",
      es: "Descargar Instagram Reels Gratis",
      ar: "تحميل Instagram Reels مجاناً",
      pt: "Baixar Instagram Reels Grátis",
      id: "Download Instagram Reels Gratis",
      fr: "Télécharger Instagram Reels Gratuitement",
      de: "Instagram Reels kostenlos herunterladen",
      ja: "Instagram Reelsを無料でダウンロード",
      tr: "Instagram Reels İndirici — Ücretsiz Kaydet",
      ru: "Скачать Instagram Reels бесплатно",
      hi: "Instagram Reels डाउनलोड करें मुफ्त में",
      vi: "Tải Instagram Reels Miễn Phí",
      th: "ดาวน์โหลด Instagram Reels ฟรี",
      it: "Scaricare Instagram Reels Gratis",
      ko: "인스타그램 릴스 무료 다운로드",
      fil: "I-download ang Instagram Reels nang Libre",
      pl: "Pobierz Instagram Reels Za Darmo",
      nl: "Instagram Reels Gratis Downloaden",
      zh: "免费下载Instagram Reels",
      uk: "Завантажити Instagram Reels безкоштовно",
    },
    descriptions: {
      en: "Download Instagram Reels and videos for free. Save any Instagram video directly to your device — no watermark, no login needed.",
      es: "Descarga Instagram Reels gratis. Sin marca de agua, sin inicio de sesión.",
      ar: "حمّل Instagram Reels مجاناً. بدون علامة مائية، بدون تسجيل دخول.",
      pt: "Baixe Instagram Reels de graça. Sem marca d'água, sem login.",
      id: "Unduh Instagram Reels gratis. Tanpa watermark, tanpa login.",
      fr: "Téléchargez Instagram Reels gratuitement. Sans filigrane ni connexion.",
      de: "Instagram Reels kostenlos herunterladen. Ohne Wasserzeichen, ohne Login.",
      ja: "Instagram Reelsを無料でダウンロード。透かしなし、ログイン不要。",
      tr: "Instagram Reels'ları ücretsiz indir. Filigransız, girişsiz.",
      ru: "Скачайте Instagram Reels бесплатно. Без водяного знака, без входа.",
      hi: "Instagram Reels मुफ्त में डाउनलोड करें। बिना वॉटरमार्क, बिना लॉगिन।",
      vi: "Tải Instagram Reels miễn phí. Không watermark, không đăng nhập.",
      th: "ดาวน์โหลด Instagram Reels ฟรี ไม่มีลายน้ำ ไม่ต้องเข้าสู่ระบบ",
      it: "Scarica Instagram Reels gratis. Senza filigrana, senza accesso.",
      ko: "인스타그램 릴스를 무료로 다운로드. 워터마크 없음, 로그인 불필요.",
      fil: "I-download ang Instagram Reels nang libre. Walang watermark, walang login.",
      pl: "Pobierz Instagram Reels za darmo. Bez znaku wodnego, bez logowania.",
      nl: "Download Instagram Reels gratis. Geen watermerk, geen login.",
      zh: "免费下载Instagram Reels。无水印，无需登录。",
      uk: "Завантажте Instagram Reels безкоштовно. Без водяного знаку, без входу.",
    },
    h1s: {
      en: "Instagram Reels Downloader",
      es: "Descargar Instagram Reels",
      ar: "تحميل Instagram Reels",
      pt: "Baixar Instagram Reels",
      id: "Download Instagram Reels",
      fr: "Télécharger Instagram Reels",
      de: "Instagram Reels Herunterladen",
      ja: "Instagram Reels ダウンロード",
      tr: "Instagram Reels İndirici",
      ru: "Скачать Instagram Reels",
      hi: "Instagram Reels डाउनलोडर",
      vi: "Tải Instagram Reels",
      th: "ดาวน์โหลด Instagram Reels",
      it: "Scaricare Instagram Reels",
      ko: "인스타그램 릴스 다운로드",
      fil: "Instagram Reels Downloader",
      pl: "Pobierz Instagram Reels",
      nl: "Instagram Reels Downloaden",
      zh: "下载Instagram Reels",
      uk: "Завантажити Instagram Reels",
    },
    intros: {
      en: "Save Instagram Reels and videos directly to your device without any login or app install. Works with all public Instagram content.",
      es: "Guarda Instagram Reels directamente sin iniciar sesión ni instalar apps.",
      ar: "احفظ Instagram Reels مباشرة على جهازك بدون تسجيل دخول.",
      pt: "Salve Reels do Instagram sem fazer login ou instalar apps.",
      id: "Simpan Instagram Reels langsung ke perangkat tanpa login.",
      fr: "Sauvegardez les Reels Instagram sans connexion ni installation d'app.",
      de: "Speichere Instagram Reels ohne Login oder App-Installation.",
      ja: "ログインやアプリなしでInstagram Reelsを保存。",
      tr: "Instagram Reels'ları giriş veya uygulama kurulumu olmadan kaydet.",
      ru: "Сохраняйте Instagram Reels без входа или установки приложения.",
      hi: "Instagram Reels को बिना लॉगिन के सीधे डाउनलोड करें।",
      vi: "Lưu Instagram Reels trực tiếp mà không cần đăng nhập.",
      th: "บันทึก Instagram Reels โดยตรงโดยไม่ต้องเข้าสู่ระบบ",
      it: "Salva Instagram Reels senza effettuare l'accesso.",
      ko: "로그인 없이 인스타그램 릴스를 직접 저장하세요.",
      fil: "I-save ang Instagram Reels nang direkta nang walang login.",
      pl: "Zapisuj Instagram Reels bez logowania się.",
      nl: "Sla Instagram Reels op zonder in te loggen.",
      zh: "无需登录即可直接保存Instagram Reels。",
      uk: "Зберігайте Instagram Reels без входу в систему.",
    },
    features: ["No login required", "No watermark", "Reels & posts", "HD quality", "Private-free", "Fast save"],
  },

  {
    platform: "facebook",
    slug_en: "facebook-video-downloader",
    titles: {
      en: "Facebook Video Downloader — Download Facebook Videos Free",
      es: "Descargar Videos de Facebook Gratis",
      ar: "تحميل فيديوهات فيسبوك مجاناً",
      pt: "Baixar Vídeos do Facebook Grátis",
      id: "Download Video Facebook Gratis",
      fr: "Télécharger des Vidéos Facebook Gratuitement",
      de: "Facebook Videos kostenlos herunterladen",
      ja: "Facebook動画を無料でダウンロード",
      tr: "Facebook Video İndirici — Ücretsiz İndir",
      ru: "Скачать видео с Facebook бесплатно",
      hi: "Facebook वीडियो डाउनलोड करें मुफ्त में",
      vi: "Tải Video Facebook Miễn Phí",
      th: "ดาวน์โหลดวิดีโอ Facebook ฟรี",
      it: "Scaricare Video Facebook Gratis",
      ko: "페이스북 동영상 무료 다운로드",
      fil: "I-download ang Facebook Videos nang Libre",
      pl: "Pobierz Filmy z Facebook Za Darmo",
      nl: "Facebook Video's Gratis Downloaden",
      zh: "免费下载Facebook视频",
      uk: "Завантажити відео з Facebook безкоштовно",
    },
    descriptions: {
      en: "Download Facebook videos in HD for free. Save Facebook posts and Reels directly. No login, no app, works on all devices.",
      es: "Descarga videos de Facebook en HD gratis. Sin inicio de sesión ni aplicación.",
      ar: "حمّل مقاطع فيسبوك بجودة HD مجاناً. بدون تسجيل دخول أو تطبيق.",
      pt: "Baixe vídeos do Facebook em HD. Sem login, sem app.",
      id: "Unduh video Facebook HD gratis. Tanpa login, tanpa aplikasi.",
      fr: "Téléchargez des vidéos Facebook en HD gratuitement. Sans connexion.",
      de: "Facebook-Videos in HD kostenlos herunterladen. Kein Login nötig.",
      ja: "FacebookのビデオをHDで無料でダウンロード。ログイン不要。",
      tr: "Facebook videolarını HD'de ücretsiz indir. Giriş gerekmez.",
      ru: "Скачивайте видео Facebook в HD качестве. Без входа.",
      hi: "Facebook वीडियो HD में मुफ्त डाउनलोड करें। बिना लॉगिन।",
      vi: "Tải video Facebook HD miễn phí. Không cần đăng nhập.",
      th: "ดาวน์โหลดวิดีโอ Facebook ในคุณภาพ HD ฟรี ไม่ต้องเข้าสู่ระบบ",
      it: "Scarica video Facebook in HD gratis. Senza accesso.",
      ko: "페이스북 동영상을 HD로 무료 다운로드. 로그인 불필요.",
      fil: "I-download ang Facebook videos sa HD nang libre. Walang login.",
      pl: "Pobierz filmy Facebook w HD za darmo. Bez logowania.",
      nl: "Download Facebook video's in HD gratis. Geen login nodig.",
      zh: "免费下载Facebook视频，高清画质，无需登录。",
      uk: "Завантажуйте відео з Facebook у HD. Без входу в систему.",
    },
    h1s: {
      en: "Facebook Video Downloader",
      es: "Descargar Videos de Facebook",
      ar: "تحميل فيديو فيسبوك",
      pt: "Baixar Vídeos do Facebook",
      id: "Download Video Facebook",
      fr: "Télécharger Vidéos Facebook",
      de: "Facebook Videos Herunterladen",
      ja: "Facebook動画ダウンロード",
      tr: "Facebook Video İndirici",
      ru: "Скачать видео Facebook",
      hi: "Facebook वीडियो डाउनलोडर",
      vi: "Tải Video Facebook",
      th: "ดาวน์โหลดวิดีโอ Facebook",
      it: "Scaricare Video Facebook",
      ko: "페이스북 동영상 다운로드",
      fil: "Facebook Video Downloader",
      pl: "Pobierz Filmy Facebook",
      nl: "Facebook Video Downloaden",
      zh: "下载Facebook视频",
      uk: "Завантажити відео Facebook",
    },
    intros: {
      en: "Download any public Facebook video in HD quality. Supports posts, Reels, and Stories. No login or account required — just paste the link.",
      es: "Descarga cualquier video público de Facebook en HD. Sin login ni cuenta.",
      ar: "حمّل أي فيديو فيسبوك عام بجودة HD. بدون تسجيل دخول.",
      pt: "Baixe qualquer vídeo público do Facebook em HD. Sem login.",
      id: "Unduh video Facebook publik apapun dalam kualitas HD. Tanpa login.",
      fr: "Téléchargez n'importe quelle vidéo Facebook publique en HD. Sans connexion.",
      de: "Lade jeden öffentlichen Facebook-Video in HD herunter. Ohne Login.",
      ja: "任意の公開FacebookビデオをHDでダウンロード。ログイン不要。",
      tr: "Herhangi bir herkese açık Facebook videosunu HD'de indir. Giriş gerekmez.",
      ru: "Скачивайте любое публичное видео Facebook в HD. Без входа.",
      hi: "किसी भी सार्वजनिक Facebook वीडियो को HD में डाउनलोड करें। बिना लॉगिन।",
      vi: "Tải bất kỳ video Facebook công khai nào trong HD. Không cần đăng nhập.",
      th: "ดาวน์โหลดวิดีโอ Facebook สาธารณะในคุณภาพ HD ไม่ต้องเข้าสู่ระบบ",
      it: "Scarica qualsiasi video Facebook pubblico in HD. Senza accesso.",
      ko: "모든 공개 페이스북 동영상을 HD로 다운로드. 로그인 불필요.",
      fil: "I-download ang anumang public na Facebook video sa HD. Walang login.",
      pl: "Pobierz dowolny publiczny film z Facebook w HD. Bez logowania.",
      nl: "Download elke publieke Facebook video in HD. Geen login nodig.",
      zh: "下载任何公开的Facebook视频，高清画质，无需登录。",
      uk: "Завантажуйте будь-яке публічне відео Facebook у HD без входу.",
    },
    features: ["HD quality", "Posts & Reels", "No login needed", "Public videos", "Fast download", "All devices"],
  },

  {
    platform: "twitter",
    slug_en: "twitter-video-downloader",
    titles: {
      en: "Twitter / X Video Downloader — Save Tweets Videos Free",
      es: "Descargar Videos de Twitter / X Gratis",
      ar: "تحميل فيديوهات تويتر / إكس مجاناً",
      pt: "Baixar Vídeos do Twitter / X Grátis",
      id: "Download Video Twitter / X Gratis",
      fr: "Télécharger des Vidéos Twitter / X Gratuitement",
      de: "Twitter / X Videos kostenlos herunterladen",
      ja: "Twitter / X動画を無料でダウンロード",
      tr: "Twitter / X Video İndirici — Ücretsiz Kaydet",
      ru: "Скачать видео с Twitter / X бесплатно",
      hi: "Twitter / X वीडियो डाउनलोड करें मुफ्त में",
      vi: "Tải Video Twitter / X Miễn Phí",
      th: "ดาวน์โหลดวิดีโอ Twitter / X ฟรี",
      it: "Scaricare Video Twitter / X Gratis",
      ko: "트위터 / X 동영상 무료 다운로드",
      fil: "I-download ang Twitter / X Videos nang Libre",
      pl: "Pobierz Filmy z Twitter / X Za Darmo",
      nl: "Twitter / X Video's Gratis Downloaden",
      zh: "免费下载Twitter / X视频",
      uk: "Завантажити відео з Twitter / X безкоштовно",
    },
    descriptions: {
      en: "Download Twitter and X videos for free in original quality. Save any tweet video directly to your device. No registration, instant download.",
      es: "Descarga videos de Twitter/X gratis en calidad original. Sin registro, descarga instantánea.",
      ar: "حمّل مقاطع تويتر وإكس مجاناً بالجودة الأصلية. بدون تسجيل.",
      pt: "Baixe vídeos do Twitter/X na qualidade original. Sem registro.",
      id: "Unduh video Twitter/X gratis dalam kualitas asli. Tanpa registrasi.",
      fr: "Téléchargez des vidéos Twitter/X en qualité originale. Sans inscription.",
      de: "Twitter/X-Videos in Originalqualität kostenlos herunterladen.",
      ja: "Twitter/XのビデオをオリジナルQualität で無料でダウンロード。",
      tr: "Twitter/X videolarını orijinal kalitede ücretsiz indir.",
      ru: "Скачивайте видео Twitter/X в оригинальном качестве. Бесплатно.",
      hi: "Twitter/X वीडियो मूल गुणवत्ता में मुफ्त डाउनलोड करें।",
      vi: "Tải video Twitter/X chất lượng gốc miễn phí.",
      th: "ดาวน์โหลดวิดีโอ Twitter/X คุณภาพดั้งเดิม ฟรี",
      it: "Scarica video Twitter/X in qualità originale. Gratis.",
      ko: "트위터/X 동영상을 원본 화질로 무료 다운로드.",
      fil: "I-download ang Twitter/X videos sa original na kalidad. Libre.",
      pl: "Pobierz filmy Twitter/X w oryginalnej jakości. Darmowy.",
      nl: "Download Twitter/X video's in originele kwaliteit. Gratis.",
      zh: "以原始质量免费下载Twitter/X视频，无需注册。",
      uk: "Завантажуйте відео Twitter/X в оригінальній якості. Безкоштовно.",
    },
    h1s: {
      en: "Twitter / X Video Downloader",
      es: "Descargar Videos de Twitter / X",
      ar: "تحميل فيديو تويتر / إكس",
      pt: "Baixar Vídeos do Twitter / X",
      id: "Download Video Twitter / X",
      fr: "Télécharger Vidéos Twitter / X",
      de: "Twitter / X Videos Herunterladen",
      ja: "Twitter / X動画ダウンロード",
      tr: "Twitter / X Video İndirici",
      ru: "Скачать видео Twitter / X",
      hi: "Twitter / X वीडियो डाउनलोडर",
      vi: "Tải Video Twitter / X",
      th: "ดาวน์โหลดวิดีโอ Twitter / X",
      it: "Scaricare Video Twitter / X",
      ko: "트위터 / X 동영상 다운로드",
      fil: "Twitter / X Video Downloader",
      pl: "Pobierz Filmy Twitter / X",
      nl: "Twitter / X Video Downloaden",
      zh: "下载Twitter / X视频",
      uk: "Завантажити відео Twitter / X",
    },
    intros: {
      en: "Save any Twitter or X video in its original quality. Download tweet videos, GIFs, and clips instantly — no account or app required.",
      es: "Guarda cualquier video de Twitter o X en calidad original. Sin cuenta ni aplicación.",
      ar: "احفظ أي فيديو من تويتر أو إكس بجودته الأصلية. بدون حساب أو تطبيق.",
      pt: "Salve qualquer vídeo do Twitter ou X na qualidade original. Sem conta.",
      id: "Simpan video Twitter atau X dalam kualitas aslinya. Tanpa akun atau aplikasi.",
      fr: "Sauvegardez n'importe quelle vidéo Twitter ou X en qualité originale.",
      de: "Speichere jeden Twitter/X-Video in Originalqualität. Kein Konto nötig.",
      ja: "TwitterやXのビデオをオリジナル品質で保存。アカウント不要。",
      tr: "Herhangi bir Twitter veya X videosunu orijinal kalitede kaydet.",
      ru: "Сохраняйте любое видео Twitter/X в оригинальном качестве. Без аккаунта.",
      hi: "किसी भी Twitter या X वीडियो को उसकी मूल गुणवत्ता में सेव करें।",
      vi: "Lưu bất kỳ video Twitter hoặc X nào theo chất lượng gốc.",
      th: "บันทึกวิดีโอ Twitter หรือ X คุณภาพดั้งเดิม ไม่ต้องมีบัญชี",
      it: "Salva qualsiasi video Twitter o X nella qualità originale.",
      ko: "Twitter 또는 X 동영상을 원본 화질로 저장. 계정 불필요.",
      fil: "I-save ang anumang Twitter o X video sa original na kalidad.",
      pl: "Zapisuj wideo Twitter lub X w oryginalnej jakości.",
      nl: "Sla elke Twitter of X video op in originele kwaliteit.",
      zh: "以原始质量保存任何Twitter或X视频，无需账户。",
      uk: "Зберігайте будь-яке відео Twitter/X в оригінальній якості.",
    },
    features: ["Original quality", "Tweet videos & GIFs", "No account needed", "No watermark", "Instant download", "All devices"],
  },
];

/* ─── LANGUAGE-SPECIFIC SLUGS ───
   Maps lang → platform_id → url slug
*/
const SEO_SLUGS = {
  en: {
    youtube:        "youtube-downloader",
    youtube_mp3:    "youtube-mp3-downloader",
    youtube_shorts: "youtube-shorts-downloader",
    tiktok:         "tiktok-downloader",
    tiktok_mp3:     "tiktok-mp3-downloader",
    instagram:      "instagram-reels-downloader",
    facebook:       "facebook-video-downloader",
    twitter:        "twitter-video-downloader",
  },
  es: {
    youtube:        "descargar-videos-youtube",
    youtube_mp3:    "youtube-mp3",
    youtube_shorts: "descargar-youtube-shorts",
    tiktok:         "descargar-tiktok",
    tiktok_mp3:     "tiktok-mp3",
    instagram:      "descargar-instagram-reels",
    facebook:       "descargar-videos-facebook",
    twitter:        "descargar-videos-twitter",
  },
  ar: {
    youtube:        "تحميل-فيديو-يوتيوب",
    youtube_mp3:    "تحميل-يوتيوب-mp3",
    youtube_shorts: "تحميل-يوتيوب-شورتس",
    tiktok:         "تحميل-فيديو-تيك-توك",
    tiktok_mp3:     "تحميل-تيك-توك-mp3",
    instagram:      "تحميل-انستغرام-ريلز",
    facebook:       "تحميل-فيديو-فيسبوك",
    twitter:        "تحميل-فيديو-تويتر",
  },
  pt: {
    youtube:        "baixar-video-youtube",
    youtube_mp3:    "youtube-para-mp3",
    youtube_shorts: "baixar-youtube-shorts",
    tiktok:         "baixar-tiktok",
    tiktok_mp3:     "tiktok-para-mp3",
    instagram:      "baixar-instagram-reels",
    facebook:       "baixar-video-facebook",
    twitter:        "baixar-video-twitter",
  },
  id: {
    youtube:        "download-video-youtube",
    youtube_mp3:    "youtube-ke-mp3",
    youtube_shorts: "download-youtube-shorts",
    tiktok:         "download-tiktok",
    tiktok_mp3:     "tiktok-ke-mp3",
    instagram:      "download-instagram-reels",
    facebook:       "download-video-facebook",
    twitter:        "download-video-twitter",
  },
  fr: {
    youtube:        "telecharger-video-youtube",
    youtube_mp3:    "youtube-vers-mp3",
    youtube_shorts: "telecharger-youtube-shorts",
    tiktok:         "telecharger-tiktok",
    tiktok_mp3:     "tiktok-vers-mp3",
    instagram:      "telecharger-instagram-reels",
    facebook:       "telecharger-video-facebook",
    twitter:        "telecharger-video-twitter",
  },
  de: {
    youtube:        "youtube-video-herunterladen",
    youtube_mp3:    "youtube-zu-mp3",
    youtube_shorts: "youtube-shorts-herunterladen",
    tiktok:         "tiktok-herunterladen",
    tiktok_mp3:     "tiktok-zu-mp3",
    instagram:      "instagram-reels-herunterladen",
    facebook:       "facebook-video-herunterladen",
    twitter:        "twitter-video-herunterladen",
  },
  ja: {
    youtube:        "youtube-ダウンロード",
    youtube_mp3:    "youtube-mp3変換",
    youtube_shorts: "youtube-shorts-ダウンロード",
    tiktok:         "tiktok-ダウンロード",
    tiktok_mp3:     "tiktok-mp3",
    instagram:      "instagram-reels-ダウンロード",
    facebook:       "facebook-動画ダウンロード",
    twitter:        "twitter-動画ダウンロード",
  },
  tr: {
    youtube:        "youtube-video-indir",
    youtube_mp3:    "youtube-mp3-indir",
    youtube_shorts: "youtube-shorts-indir",
    tiktok:         "tiktok-indir",
    tiktok_mp3:     "tiktok-mp3-indir",
    instagram:      "instagram-reels-indir",
    facebook:       "facebook-video-indir",
    twitter:        "twitter-video-indir",
  },
  ru: {
    youtube:        "скачать-видео-youtube",
    youtube_mp3:    "youtube-в-mp3",
    youtube_shorts: "скачать-youtube-shorts",
    tiktok:         "скачать-тикток",
    tiktok_mp3:     "тикток-в-mp3",
    instagram:      "скачать-instagram-reels",
    facebook:       "скачать-видео-facebook",
    twitter:        "скачать-видео-twitter",
  },
  hi: {
    youtube:        "youtube-video-download",
    youtube_mp3:    "youtube-mp3-download",
    youtube_shorts: "youtube-shorts-download",
    tiktok:         "tiktok-video-download",
    tiktok_mp3:     "tiktok-mp3-download",
    instagram:      "instagram-reels-download",
    facebook:       "facebook-video-download",
    twitter:        "twitter-video-download",
  },
  vi: {
    youtube:        "tai-video-youtube",
    youtube_mp3:    "youtube-sang-mp3",
    youtube_shorts: "tai-youtube-shorts",
    tiktok:         "tai-tiktok",
    tiktok_mp3:     "tiktok-sang-mp3",
    instagram:      "tai-instagram-reels",
    facebook:       "tai-video-facebook",
    twitter:        "tai-video-twitter",
  },
  th: {
    youtube:        "โหลดวิดีโอ-youtube",
    youtube_mp3:    "youtube-เป็น-mp3",
    youtube_shorts: "โหลด-youtube-shorts",
    tiktok:         "โหลด-tiktok",
    tiktok_mp3:     "tiktok-เป็น-mp3",
    instagram:      "โหลด-instagram-reels",
    facebook:       "โหลดวิดีโอ-facebook",
    twitter:        "โหลดวิดีโอ-twitter",
  },
  it: {
    youtube:        "scaricare-video-youtube",
    youtube_mp3:    "youtube-in-mp3",
    youtube_shorts: "scaricare-youtube-shorts",
    tiktok:         "scaricare-tiktok",
    tiktok_mp3:     "tiktok-in-mp3",
    instagram:      "scaricare-instagram-reels",
    facebook:       "scaricare-video-facebook",
    twitter:        "scaricare-video-twitter",
  },
  ko: {
    youtube:        "유튜브-동영상-다운로드",
    youtube_mp3:    "유튜브-mp3-변환",
    youtube_shorts: "유튜브-쇼츠-다운로드",
    tiktok:         "틱톡-다운로드",
    tiktok_mp3:     "틱톡-mp3",
    instagram:      "인스타그램-릴스-다운로드",
    facebook:       "페이스북-동영상-다운로드",
    twitter:        "트위터-동영상-다운로드",
  },
  fil: {
    youtube:        "youtube-video-download",
    youtube_mp3:    "youtube-sa-mp3",
    youtube_shorts: "youtube-shorts-download",
    tiktok:         "tiktok-download",
    tiktok_mp3:     "tiktok-sa-mp3",
    instagram:      "instagram-reels-download",
    facebook:       "facebook-video-download",
    twitter:        "twitter-video-download",
  },
  pl: {
    youtube:        "pobierz-video-youtube",
    youtube_mp3:    "youtube-do-mp3",
    youtube_shorts: "pobierz-youtube-shorts",
    tiktok:         "pobierz-tiktok",
    tiktok_mp3:     "tiktok-do-mp3",
    instagram:      "pobierz-instagram-reels",
    facebook:       "pobierz-video-facebook",
    twitter:        "pobierz-video-twitter",
  },
  nl: {
    youtube:        "youtube-video-downloaden",
    youtube_mp3:    "youtube-naar-mp3",
    youtube_shorts: "youtube-shorts-downloaden",
    tiktok:         "tiktok-downloaden",
    tiktok_mp3:     "tiktok-naar-mp3",
    instagram:      "instagram-reels-downloaden",
    facebook:       "facebook-video-downloaden",
    twitter:        "twitter-video-downloaden",
  },
  zh: {
    youtube:        "下载youtube视频",
    youtube_mp3:    "youtube转mp3",
    youtube_shorts: "下载youtube-shorts",
    tiktok:         "下载tiktok视频",
    tiktok_mp3:     "tiktok转mp3",
    instagram:      "下载instagram-reels",
    facebook:       "下载facebook视频",
    twitter:        "下载twitter视频",
  },
  uk: {
    youtube:        "завантажити-відео-youtube",
    youtube_mp3:    "youtube-в-mp3",
    youtube_shorts: "завантажити-youtube-shorts",
    tiktok:         "завантажити-tiktok",
    tiktok_mp3:     "tiktok-в-mp3",
    instagram:      "завантажити-instagram-reels",
    facebook:       "завантажити-відео-facebook",
    twitter:        "завантажити-відео-twitter",
  },
};

/* ─── RELATED TOOL LABELS ─── */
const RELATED_LABELS = {
  youtube:        { en:"YouTube Downloader", es:"Descargar YouTube", ar:"تحميل يوتيوب", pt:"Baixar YouTube", id:"Download YouTube", fr:"Télécharger YouTube", de:"YouTube Herunterladen", ja:"YouTube DL", tr:"YouTube İndir", ru:"YouTube Скачать", hi:"YouTube डाउनलोड", vi:"Tải YouTube", th:"โหลด YouTube", it:"Scarica YouTube", ko:"유튜브 DL", fil:"YouTube Download", pl:"Pobierz YouTube", nl:"YouTube Downloaden", zh:"下载YouTube", uk:"YouTube DL" },
  youtube_mp3:    { en:"YouTube MP3", es:"YouTube MP3", ar:"يوتيوب MP3", pt:"YouTube MP3", id:"YouTube MP3", fr:"YouTube MP3", de:"YouTube MP3", ja:"YouTube MP3", tr:"YouTube MP3", ru:"YouTube MP3", hi:"YouTube MP3", vi:"YouTube MP3", th:"YouTube MP3", it:"YouTube MP3", ko:"YouTube MP3", fil:"YouTube MP3", pl:"YouTube MP3", nl:"YouTube MP3", zh:"YouTube MP3", uk:"YouTube MP3" },
  youtube_shorts: { en:"YT Shorts Downloader", es:"YT Shorts", ar:"يوتيوب شورتس", pt:"YT Shorts", id:"YT Shorts", fr:"YT Shorts", de:"YT Shorts", ja:"YT Shorts", tr:"YT Shorts", ru:"YT Shorts", hi:"YT Shorts", vi:"YT Shorts", th:"YT Shorts", it:"YT Shorts", ko:"YT 쇼츠", fil:"YT Shorts", pl:"YT Shorts", nl:"YT Shorts", zh:"YT Shorts", uk:"YT Shorts" },
  tiktok:         { en:"TikTok Downloader", es:"Descargar TikTok", ar:"تحميل تيك توك", pt:"Baixar TikTok", id:"Download TikTok", fr:"Télécharger TikTok", de:"TikTok Herunterladen", ja:"TikTok DL", tr:"TikTok İndir", ru:"TikTok Скачать", hi:"TikTok डाउनलोड", vi:"Tải TikTok", th:"โหลด TikTok", it:"Scarica TikTok", ko:"틱톡 DL", fil:"TikTok Download", pl:"Pobierz TikTok", nl:"TikTok Downloaden", zh:"下载TikTok", uk:"TikTok DL" },
  tiktok_mp3:     { en:"TikTok MP3", es:"TikTok MP3", ar:"تيك توك MP3", pt:"TikTok MP3", id:"TikTok MP3", fr:"TikTok MP3", de:"TikTok MP3", ja:"TikTok MP3", tr:"TikTok MP3", ru:"TikTok MP3", hi:"TikTok MP3", vi:"TikTok MP3", th:"TikTok MP3", it:"TikTok MP3", ko:"틱톡 MP3", fil:"TikTok MP3", pl:"TikTok MP3", nl:"TikTok MP3", zh:"TikTok MP3", uk:"TikTok MP3" },
  instagram:      { en:"Instagram Reels", es:"Instagram Reels", ar:"انستغرام ريلز", pt:"Instagram Reels", id:"Instagram Reels", fr:"Instagram Reels", de:"Instagram Reels", ja:"Instagram Reels", tr:"Instagram Reels", ru:"Instagram Reels", hi:"Instagram Reels", vi:"Instagram Reels", th:"Instagram Reels", it:"Instagram Reels", ko:"인스타 릴스", fil:"Instagram Reels", pl:"Instagram Reels", nl:"Instagram Reels", zh:"Instagram Reels", uk:"Instagram Reels" },
  facebook:       { en:"Facebook Downloader", es:"Descargar Facebook", ar:"تحميل فيسبوك", pt:"Baixar Facebook", id:"Download Facebook", fr:"Télécharger Facebook", de:"Facebook Herunterladen", ja:"Facebook DL", tr:"Facebook İndir", ru:"Facebook Скачать", hi:"Facebook डाउनलोड", vi:"Tải Facebook", th:"โหลด Facebook", it:"Scarica Facebook", ko:"페이스북 DL", fil:"Facebook Download", pl:"Pobierz Facebook", nl:"Facebook Downloaden", zh:"下载Facebook", uk:"Facebook DL" },
  twitter:        { en:"Twitter / X Downloader", es:"Descargar Twitter", ar:"تحميل تويتر", pt:"Baixar Twitter", id:"Download Twitter", fr:"Télécharger Twitter", de:"Twitter Herunterladen", ja:"Twitter DL", tr:"Twitter İndir", ru:"Twitter Скачать", hi:"Twitter डाउनलोड", vi:"Tải Twitter", th:"โหลด Twitter", it:"Scarica Twitter", ko:"트위터 DL", fil:"Twitter Download", pl:"Pobierz Twitter", nl:"Twitter Downloaden", zh:"下载Twitter", uk:"Twitter DL" },
};

/* ─── SECTION LABELS ─── */
const SECTION_LABELS = {
  related_tools:  { en:"Related Tools", es:"Herramientas relacionadas", ar:"أدوات ذات صلة", pt:"Ferramentas relacionadas", id:"Alat terkait", fr:"Outils associés", de:"Ähnliche Tools", ja:"関連ツール", tr:"İlgili araçlar", ru:"Похожие инструменты", hi:"संबंधित उपकरण", vi:"Công cụ liên quan", th:"เครื่องมือที่เกี่ยวข้อง", it:"Strumenti correlati", ko:"관련 도구", fil:"Mga Kaugnay na Tool", pl:"Powiązane narzędzia", nl:"Gerelateerde tools", zh:"相关工具", uk:"Пов'язані інструменти" },
  how_it_works:   { en:"How It Works", es:"Cómo funciona", ar:"كيف يعمل", pt:"Como funciona", id:"Cara kerjanya", fr:"Comment ça marche", de:"So funktioniert es", ja:"使い方", tr:"Nasıl çalışır", ru:"Как это работает", hi:"यह कैसे काम करता है", vi:"Cách thức hoạt động", th:"วิธีการทำงาน", it:"Come funziona", ko:"작동 방식", fil:"Paano ito gumagana", pl:"Jak to działa", nl:"Hoe het werkt", zh:"如何工作", uk:"Як це працює" },
  key_features:   { en:"Key Features", es:"Características principales", ar:"الميزات الرئيسية", pt:"Recursos principais", id:"Fitur utama", fr:"Fonctionnalités clés", de:"Hauptfunktionen", ja:"主な機能", tr:"Temel özellikler", ru:"Ключевые функции", hi:"मुख्य विशेषताएं", vi:"Tính năng chính", th:"คุณสมบัติหลัก", it:"Funzionalità principali", ko:"주요 기능", fil:"Mga Pangunahing Feature", pl:"Kluczowe funkcje", nl:"Belangrijkste functies", zh:"主要特点", uk:"Ключові функції" },
  start_download: { en:"Start Downloading Now", es:"Empezar a descargar", ar:"ابدأ التحميل الآن", pt:"Começar a baixar", id:"Mulai unduh sekarang", fr:"Commencer le téléchargement", de:"Jetzt herunterladen", ja:"今すぐダウンロード開始", tr:"İndirmeye Başla", ru:"Начать скачивание", hi:"अभी डाउनलोड शुरू करें", vi:"Bắt đầu tải xuống", th:"เริ่มดาวน์โหลดตอนนี้", it:"Inizia a scaricare ora", ko:"지금 다운로드 시작", fil:"Simulan ang pag-download", pl:"Zacznij pobierać", nl:"Begin nu te downloaden", zh:"立即开始下载", uk:"Почати завантаження" },
  step1_title:    { en:"Paste the Link", es:"Pega el enlace", ar:"الصق الرابط", pt:"Cole o link", id:"Tempel tautan", fr:"Collez le lien", de:"Link einfügen", ja:"リンクを貼り付け", tr:"Bağlantıyı yapıştır", ru:"Вставить ссылку", hi:"लिंक पेस्ट करें", vi:"Dán liên kết", th:"วางลิงก์", it:"Incolla il link", ko:"링크 붙여넣기", fil:"I-paste ang link", pl:"Wklej link", nl:"Plak de link", zh:"粘贴链接", uk:"Вставити посилання" },
  step1_desc:     { en:"Copy the video URL and paste it into the input field above.", es:"Copia la URL del video y pégala en el campo de arriba.", ar:"انسخ رابط الفيديو والصقه في حقل الإدخال أعلاه.", pt:"Copie a URL do vídeo e cole no campo acima.", id:"Salin URL video dan tempel di kolom di atas.", fr:"Copiez l'URL de la vidéo et collez-la dans le champ ci-dessus.", de:"Kopiere die Video-URL und füge sie oben ein.", ja:"動画URLをコピーして上の入力欄に貼り付けてください。", tr:"Video URL'sini kopyala ve yukarıdaki alana yapıştır.", ru:"Скопируйте URL видео и вставьте в поле выше.", hi:"वीडियो URL कॉपी करें और ऊपर के इनपुट में पेस्ट करें।", vi:"Sao chép URL video và dán vào ô nhập ở trên.", th:"คัดลอก URL วิดีโอแล้ววางในช่องด้านบน", it:"Copia l'URL del video e incollala nel campo sopra.", ko:"동영상 URL을 복사하고 위 입력 창에 붙여넣으세요.", fil:"Kopyahin ang video URL at i-paste sa field sa itaas.", pl:"Skopiuj URL wideo i wklej w pole powyżej.", nl:"Kopieer de video-URL en plak die in het veld hierboven.", zh:"复制视频URL并粘贴到上面的输入框中。", uk:"Скопіюйте URL відео та вставте у поле вище." },
  step2_title:    { en:"Choose Format", es:"Elige el formato", ar:"اختر الصيغة", pt:"Escolha o formato", id:"Pilih format", fr:"Choisissez le format", de:"Format wählen", ja:"フォーマットを選択", tr:"Format seç", ru:"Выбрать формат", hi:"फॉर्मेट चुनें", vi:"Chọn định dạng", th:"เลือกรูปแบบ", it:"Scegli il formato", ko:"형식 선택", fil:"Pumili ng format", pl:"Wybierz format", nl:"Kies formaat", zh:"选择格式", uk:"Вибрати формат" },
  step2_desc:     { en:"Select MP4 video or MP3 audio depending on what you need.", es:"Elige MP4 o MP3 según lo que necesites.", ar:"اختر MP4 فيديو أو MP3 صوت حسب ما تحتاج.", pt:"Selecione MP4 ou MP3 conforme necessário.", id:"Pilih MP4 video atau MP3 audio.", fr:"Sélectionnez MP4 ou MP3 selon vos besoins.", de:"Wähle MP4 oder MP3 je nach Bedarf.", ja:"必要に応じてMP4またはMP3を選択してください。", tr:"İhtiyacına göre MP4 veya MP3 seç.", ru:"Выберите MP4 или MP3 в зависимости от потребностей.", hi:"अपनी जरूरत के अनुसार MP4 वीडियो या MP3 ऑडियो चुनें।", vi:"Chọn MP4 hoặc MP3 tùy nhu cầu.", th:"เลือก MP4 หรือ MP3 ตามที่ต้องการ", it:"Seleziona MP4 o MP3 in base alle tue esigenze.", ko:"필요에 따라 MP4 또는 MP3를 선택하세요.", fil:"Pumili ng MP4 o MP3 ayon sa iyong pangangailangan.", pl:"Wybierz MP4 lub MP3 w zależności od potrzeb.", nl:"Kies MP4 of MP3 afhankelijk van je behoeften.", zh:"根据需要选择MP4视频或MP3音频。", uk:"Виберіть MP4 чи MP3 залежно від потреби." },
  step3_title:    { en:"Download Instantly", es:"Descarga al instante", ar:"حمّل فوراً", pt:"Baixar instantaneamente", id:"Unduh seketika", fr:"Télécharger instantanément", de:"Sofort herunterladen", ja:"すぐにダウンロード", tr:"Anında indir", ru:"Мгновенно скачать", hi:"तुरंत डाउनलोड करें", vi:"Tải xuống ngay", th:"ดาวน์โหลดทันที", it:"Scarica istantaneamente", ko:"즉시 다운로드", fil:"I-download agad", pl:"Pobierz natychmiast", nl:"Direct downloaden", zh:"立即下载", uk:"Завантажити миттєво" },
  step3_desc:     { en:"Click the download button and save the file to your device.", es:"Haz clic en descargar y guarda el archivo.", ar:"اضغط على زر التحميل واحفظ الملف.", pt:"Clique em baixar e salve o arquivo.", id:"Klik tombol unduh dan simpan file.", fr:"Cliquez sur télécharger et sauvegardez le fichier.", de:"Klicke auf herunterladen und speichere die Datei.", ja:"ダウンロードボタンをクリックしてファイルを保存。", tr:"İndir butonuna bas ve dosyayı kaydet.", ru:"Нажмите кнопку загрузки и сохраните файл.", hi:"डाउनलोड बटन दबाएं और फ़ाइल सेव करें।", vi:"Nhấp vào nút tải xuống và lưu tệp.", th:"คลิกปุ่มดาวน์โหลดแล้วบันทึกไฟล์", it:"Clicca sul pulsante scarica e salva il file.", ko:"다운로드 버튼을 클릭하고 파일을 저장하세요.", fil:"I-click ang download button at i-save ang file.", pl:"Kliknij pobierz i zapisz plik.", nl:"Klik op downloaden en sla het bestand op.", zh:"点击下载按钮并保存文件。", uk:"Натисніть кнопку завантаження і збережіть файл." },
};

/* Utility: get text for a lang with en fallback */
function t(obj, lang) {
  return (obj && (obj[lang] || obj["en"])) || "";
}

/* Utility: get SEO page data by platform */
function getSEOPage(platformId) {
  return SEO_PAGES.find(p => p.platform === platformId) || null;
}

/* Utility: get slug for lang+platform */
function getSlug(lang, platformId) {
  return (SEO_SLUGS[lang] && SEO_SLUGS[lang][platformId]) || SEO_SLUGS.en[platformId] || platformId;
}

/* Build a reverse lookup: slug → {lang, platformId} for all languages */
function buildSlugIndex() {
  const index = {};
  for (const [lang, platforms] of Object.entries(SEO_SLUGS)) {
    for (const [platformId, slug] of Object.entries(platforms)) {
      const key = `${lang}:${slug}`;
      index[key] = { lang, platformId };
    }
  }
  return index;
}

module.exports = {
  PLATFORMS,
  SEO_PAGES,
  SEO_SLUGS,
  RELATED_LABELS,
  SECTION_LABELS,
  t,
  getSEOPage,
  getSlug,
  buildSlugIndex,
};
